### ISSUE TITLE
prometheus_node_exporter_textfiles_directory undefined

### ISSUE THREAD

**Issue by shaunrampersad** [mesaguy/ansible-prometheus#25]
Hi

Version: v0.12.22

Hitting an issue with a variable being undefined. 

```
The error was: 'prometheus_node_exporter_textfiles_directory' is undefined
The error appears to be in '../roles/mesaguy.prometheus/tasks/main.yml': line 2, column 3,
```

Docs describe the variables purpose, but there is no default set for it. 
```The directory node_exporter should poll for text files containing additional information to present. Defaults to '/opt/prometheus/etc/node_exporter_textfiles':

    prometheus_node_exporter_textfiles_directory: '/opt/prometheus/etc/node_exporter_textfiles'
```

Maybe this needs to be added to defaults?

**Comment by mesaguy** [comment]
Confirmed, fixed with 7bd4036f7dd5c8178b234706241a359c79580ce0

**Comment by f9n** [comment]
Same on v0.12.25
```
fatal: [default]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'prometheus_node_exporter_textfiles_directory' is undefined\n\nThe error appears to be in '/home/packer/.ansible/roles/mesaguy.prometheus/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Set global facts to be used inside and outside of role\n  ^ here\n"}
```

My usage:

```yaml
    - role: mesaguy.prometheus
      vars:
        prometheus_manage_client_tgroups: false
        prometheus_components:
          - node_exporter
```
